#!/usr/bin/env bash
# This script configures a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; }' /etc/nginx/sites-available/default
service nginx restart
