#!/usr/bin/env bash
# FizzBuzz: This scripts that displays numbers from 1 to 100
x=1
while [ $x -le 100 ]; do
    if [ $((x % 3)) -eq 0 ] && [ $((x % 5)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((x % 3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $((x % 5)) -eq 0 ]
    then
	echo "Buzz"
    else
	echo $x
    fi
    x=$((x + 1))
done
