#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
x=0
while [ $x -le 12 ]; do
    echo "Hour: $x"
    y=1
    while [ $y -le 59 ]; do
	echo "$y"
	y=$((y + 1))
    done
    x=$((x + 1))
done
