#!/usr/bin/env bash
# This script displays the content of the current directory in a list format where only the part of the name after the first path is displayed
for i in $(find ./* | cut -d / -f 2 | cut -d - -f 2); do
    echo "$i"
done
