#!/usr/bin/env bash
# This script configures an Ubuntu server
cp /etc/hosts ~/hosts.new
echo -e "127.0.0.2 \t localhost" > ~/hosts.new
echo -e "8.8.8.8 \t facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
