#!/usr/bin/env bash
# Bash script that configures a container to fit the requirements
pkill -f apache2
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "1s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
